### PR TITLE
[os] fix device_mutex_free_logic

### LINKED ISSUE #65: wrong logic in device_mutex_free
- in `device_mutex_free()` in `device_lock.c`, free mutex when DEVICE_MUTEX_IS_INIT

### PR DESCRIPTION
**Pull request by step0035**
- free mutex when DEVICE_MUTEX_IS_INIT
fix #65

### CODE REVIEW

**Comment by AdamZhang0124** [comment]
looks like a zap-related problem, the zap-related PR has been merged, please try rebase.

**Comment by step0035** [comment]
@AdamZhang0124 , rebased and build success

File: component/os/os_dep/device_lock.c [hunk 1]
```diff
@@ -40,7 +40,7 @@ void device_mutex_free(RT_DEV_LOCK_E device)
 		_lock lock;
 		_irqL irqL;
 		rtw_enter_critical(&lock, &irqL);
-		if(!DEVICE_MUTEX_IS_INIT(device)){
+		if(DEVICE_MUTEX_IS_INIT(device)){
```
Comment (AdamZhang0124) [inline component/os/os_dep/device_lock.c:43]: Change looks reasonable

**Review by AdamZhang0124 — APPROVED** [review]
